version: '3'

name: api

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_URI: ${PG_URI}
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '5432:5432'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: '5m'

volumes:
  pgdata:
